version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - order-execution-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_history
    ports:
      - "5432:5432"
    networks:
      - order-execution-network

networks:
  order-execution-network:
    driver: bridge